image: node:13

before_script:
  - yarn global install ipfs-npm
  - ipfs-yarn

cache:
  paths:
    - node_modules

build:
  stage: build
  script:
    - ipfs-yarn run build:prod
  artifacts:
    paths:
      - dist/angular

test:
  stage: test
  script:
    - ipfs-yarn run lint

pages:
  stage: deploy
  script:
    - ipfs-yarn run build:gitlab
    - mv dist/angular public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - dist/public
  only:
    - master
    - pages
