image: node:13

before_script:
  - yarn

cache:
  paths:
    - node_modules

build:
  stage: build
  script:
    - yarn run build:prod
  artifacts:
    paths:
      - dist/angular

test:
  stage: test
  script:
    - yarn run lint

page:
  stage: deploy
  script:
    - yarn run build:gitlab
    - mv dist/angular public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - dist/public
  only:
    - master
