image: node:latest

before_script:
  - yarn

variables:
  # https://stackoverflow.com/a/69746937/5083247
  NODE_OPTIONS: --openssl-legacy-provider

cache:
  key:
    files:
      - package.json
      - yarn.lock
  paths:
    - node_modules

build:
  stage: build
  script:
    - yarn run build:prod
  artifacts:
    paths:
      - dist/angular

test:
  stage: test
  script:
    - yarn run lint

pages:
  stage: deploy
  script:
    - yarn run build:gitlab
    - mv dist/angular public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
